.PHONY: clean All

All:
	@echo "----------Building project:[ Workspace1 - Debug ]----------"
	@cd "Workspace1" && "$(MAKE)" -f  "Workspace1.mk"
clean:
	@echo "----------Cleaning project:[ Workspace1 - Debug ]----------"
	@cd "Workspace1" && "$(MAKE)" -f  "Workspace1.mk" clean
